### ISSUE TITLE
Link from Awesome

### ISSUE THREAD

**Issue by MeirionHughes** [Level/awesome#2]
Should get ourselves into https://github.com/sindresorhus/awesome 66K stars. :D

I'm thinking under `Databases` as `Level`. not sure about the description though. ❓

**Comment by vweevers** [comment]
Many of the items there don't have a description, maybe we don't need one either

**Comment by ralphtheninja** [comment]
Good idea!

**Comment by MeirionHughes** [comment]
okay-doky, I'll make the pr when #3 is ready - they are vetted.

**Comment by ralphtheninja** [comment]
https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list

We fail one of the requirements `Non-generated Markdown file in a GitHub repo`

**Comment by vweevers** [comment]
There are more rules I don't agree with.

> - It's the result of hard work and the best I could possibly produce.
> - Only has awesome items. Awesome lists are curations of the best, not everything.

Though Level has been maturing, the wider ecosystem is still a playground. I love that. There is value in any contribution. Do the best you can, it doesn't have to be perfect now, or tomorrow. You are a magic thing anyhow. Experiment first, tweak later. Who's to say what's awesome? I don't want to curate. The levelup wiki is filled with fun things, because it *isn't* curated.

I'm fine with not being "awesome" :)

**Comment by vweevers** [comment]
I vote to close this.
