### ISSUE TITLE
please add a 'last commit date' column

### ISSUE THREAD

**Issue by bionicles** [Level/awesome#53]
it would be awesome to quickly see the date of the last commit on the project, and perhaps the number of stars, so we could quickly sort out the stale repos from the fresh ones!

thanks for making this!

**Comment by ad-m** [comment]
We can use https://shields.io/category/activity to add badge about "GitHub commit activity" and https://shields.io/category/social to add badge about "GitHub Repo stars".

**Comment by vweevers** [comment]
Personally I wouldn't use last commit as a metric, because it discounts stable repo's, as well as old yet interesting ideas that can be forked at will. That said, folks can interpret the displayed data according to their own preferences and needs.

A badge is a good idea. But we're running out of space. We could replace the tables with a section per module, e.g.:

---

## Stores

Modules that implement [`abstract-leveldown`](https://github.com/Level/abstract-leveldown) as storage for [`levelup`](https://github.com/Level/levelup).

### [`leveldown`](https://github.com/Level/leveldown)

[![abstract-leveldown](https://img.shields.io/badge/abstract--leveldown-6.2-yellow.svg)](https://github.com/Level/leveldown/network/dependencies) [![dependencies](https://img.shields.io/david/Level/leveldown.svg)](https://david-dm.org/Level/leveldown) [![last commit](https://img.shields.io/github/last-commit/Level/leveldown)](https://github.com/Level/leveldown) [![contributors](https://img.shields.io/github/contributors/Level/leveldown)](https://github.com/Level/leveldown/graphs/contributors)

[LevelDB](https://github.com/google/leveldb) store.

### [`memdown`](https://github.com/Level/memdown)

...

**Comment by bionicles** [comment]
that looks beautiful @vweevers
